# Generated by Django 3.2.3 on 2021-06-01 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_auto_20210531_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gretting',
            name='temp',
        ),
    ]
